[package]
name = "ch04"
version = "0.1.0"
authors = ["mikong <4162+mikong@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand_os = "0.2.1"
sha2 = "0.8.0"
hex-literal = "0.2.0"
# Exercise 4.2
num-bigint = "0.2"
num-traits = "0.2.8"
# Exercise 4.3
openssl-sys = "0.9"
openssl = "0.10"
